version: '2'
services:
    noteshare-app:
        image: noteshare
        external_links:
            - noteshare-mysql:mysql
            - noteshare-elasticsearch:elasticsearch
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/noteshare?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300
        ports:
            - 192.99.134.92:8181:8080
    noteshare-mysql:
        extends:
            file: mysql.yml
            service: noteshare-mysql
    noteshare-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: noteshare-elasticsearch
